# Generated by Django 5.0.3 on 2024-05-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_seminario_alter_documento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Guia', 'Guía'), ('Formato', 'Formato'), ('Ejemplo', 'Ejemplo')], max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
