# Generated by Django 5.0.3 on 2024-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_materialapoyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialapoyo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
