# Generated by Django 5.0.3 on 2024-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_materialapoyo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
