# Generated by Django 5.0.3 on 2024-05-27 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_alter_documento_url'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisado', models.BooleanField(default=False)),
                ('titulo_adecuado', models.BooleanField(blank=True, null=True)),
                ('objetivos_cumplidos', models.BooleanField(blank=True, null=True)),
                ('referencias_correctas', models.BooleanField(blank=True, null=True)),
                ('errores_ortograficos', models.BooleanField(blank=True, null=True)),
                ('estructura_clara', models.BooleanField(blank=True, null=True)),
                ('contenido_coherente', models.BooleanField(blank=True, null=True)),
                ('normas_formato', models.BooleanField(blank=True, null=True)),
                ('metodologia_descrita', models.BooleanField(blank=True, null=True)),
                ('resultados_presentados', models.BooleanField(blank=True, null=True)),
                ('discusion_adecuada', models.BooleanField(blank=True, null=True)),
                ('conclusiones_pertinentes', models.BooleanField(blank=True, null=True)),
                ('suficientes_referencias', models.BooleanField(blank=True, null=True)),
                ('introduccion_contextualiza', models.BooleanField(blank=True, null=True)),
                ('graficos_tablas_adecuados', models.BooleanField(blank=True, null=True)),
                ('resumen_claro_conciso', models.BooleanField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('documento_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnos.documento_alumno')),
            ],
        ),
    ]
