# Generated by Django 5.0.3 on 2024-05-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_revisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisado',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
