# Generated by Django 5.0.3 on 2024-05-31 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_revisado_aceptado'),
        ('alumnos', '0005_documentopropuestaalumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisarPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisado', models.BooleanField(default=False)),
                ('titulo_adecuado', models.BooleanField(blank=True, null=True)),
                ('objetivos_planteados', models.BooleanField(blank=True, null=True)),
                ('referencias_correctas', models.BooleanField(blank=True, null=True)),
                ('errores_ortograficos', models.BooleanField(blank=True, null=True)),
                ('normas_formato', models.BooleanField(blank=True, null=True)),
                ('metodologia_descrita', models.BooleanField(blank=True, null=True)),
                ('suficientes_referencias', models.BooleanField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('aceptado', models.BooleanField(default=False)),
                ('documento_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumnos.documentopropuestaalumno')),
            ],
        ),
    ]
