# Generated by Django 5.0.3 on 2024-05-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento_alumno',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento_alumno',
            name='en_correccion',
            field=models.BooleanField(default=False),
        ),
    ]
