# Generated by Django 5.0.3 on 2024-05-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_documento_alumno_aceptado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoTitulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_info', models.IntegerField(default=0)),
                ('enviar_propuesta', models.IntegerField(default=0)),
                ('resultado_propuesta', models.IntegerField(default=0)),
                ('desarrollo_proyecto', models.IntegerField(default=0)),
                ('enviar_trabajo', models.IntegerField(default=0)),
            ],
        ),
    ]
