# Generated by Django 5.0.3 on 2024-05-31 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_procesotitulacion_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPropuestaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('nombre_directores', models.CharField(max_length=255)),
                ('resumen', models.TextField()),
                ('objetivos', models.TextField()),
                ('metodologia', models.TextField()),
                ('palabras_clave', models.CharField(max_length=255)),
                ('referencias', models.TextField()),
                ('convocatoria', models.CharField(default='2024', max_length=4)),
                ('enviado', models.BooleanField(default=False)),
                ('aceptado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
