# Generated by Django 5.0.3 on 2024-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_documentopropuestaalumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='documentopropuestaalumno',
            name='directores',
            field=models.ManyToManyField(blank=True, to='alumnos.directores'),
        ),
    ]
