# Generated by Django 5.0.3 on 2024-06-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_remove_revisado_aceptado_remove_revisado_comentarios_and_more'),
        ('alumnos', '0009_sinodalasignado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento_alumno',
        ),
    ]
